### PR TITLE
Analysis Notebook for blog

### PR DESCRIPTION
**Pull request by tylerganter**
I saved a snapshot of the database as a CSV file (and added a script to generate this CSV at any time).

I then made a notebook to interactively develop the PDI statistic. I plan to use this for making plots for a blog post and also link to this notebook in the article.

### CODE REVIEW

**Review by ehofesmann — COMMENTED** [review]
`time_square` should be renamed to `times_square` in the example data and notebook. Just in case someone from NY goes through it and gets upset that we're using the wrong name. Otherwise, the notebook is awesome! Great guide!

**Review by ehofesmann — COMMENTED** [review]
In the notebook, you should probably move the text from below cell 3 to below cell 4 and plot the graph before analyzing it.

**Comment by tylerganter** [comment]
> In the notebook, you should probably move the text from below cell 3 to below cell 4 and plot the graph before analyzing it.

This is a bit of a matter of opinion isn't it? People using this notebook are going to have access to the pre-computed plots. The value of it being a notebook is moreover to see the code and play with it if so desired.

**Review by ehofesmann — APPROVED** [review]
Sure, it was really a minor point. Great walk through and explanations! Good job!

**Pull request merged**
