### PR TITLE
Switching to on hover for image overlay

### PR DESCRIPTION
**Pull request by benjaminpkane**
I am not convinced this makes for a better overall experience. Adding hover removes the need to have the close icon on the overlay, as onclick is no longer needed.

@lethosor Can you try test this? What are your thoughts?

### CODE REVIEW

**Comment by lethosor** [comment]
Yeah, this is sending and cancelling a lot of image requests. Probably want to add some debouncing.

Another thought: it would be nice for clicking to still "lock in" an image. It's no longer possible to right-click the image since it disappears before you can get to it, for example.

**Comment by brimoor** [comment]
I like Alan's idea of still allowing click to lock-in an image

**Comment by benjaminpkane** [comment]
I pulled the trigger on this and just deployed. @lethosor I know this PR is all jumbled now. Can we merge this?

Last time I mix work in PRs :smile:

**Review by lethosor — APPROVED** [review]
Made a couple tweaks, LGTM (and on mobile too) - nice!

**Pull request merged**
